/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tpvo;

import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author 2417011
 */
public class CategoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form CategoryPanel
     */
    public CategoryPanel() {
        initComponents();
         DefaultMutableTreeNode root = new DefaultMutableTreeNode("Tous les Livres");

        // Add child nodes
        DefaultMutableTreeNode historique = new DefaultMutableTreeNode("historique");
        historique.add(new DefaultMutableTreeNode("bataille d alger"));
        historique.add(new DefaultMutableTreeNode("Nelson Mandela"));

        DefaultMutableTreeNode sport = new DefaultMutableTreeNode("sport");
        DefaultMutableTreeNode football = new DefaultMutableTreeNode("football");
        football.add(new DefaultMutableTreeNode("messi"));
        football.add(new DefaultMutableTreeNode("Ronaldo-CR7"));

        DefaultMutableTreeNode Automobile = new DefaultMutableTreeNode("Automobile");
        Automobile.add(new DefaultMutableTreeNode("nissan GTR"));

        sport.add(football);
        sport.add(Automobile);

        root.add(historique);
        root.add(sport);

        // Create the tree
        JTree categoryTree = new JTree(root);

        // Add the tree to the scroll pane
        jScrollPane1.setViewportView(categoryTree);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
